version: '3'
services:
#  app:
#    build:
#      context: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#      - ollama
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./volumes/ollama:/root/.ollama
  postgres:
    image: ankane/pgvector
    ports:
      - "5433:5432"
    expose:
      - 5433
      - 5432
    restart: always
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=movie_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
