spring:
  application:
    name: movie-hybrid-search
  ai:
    ollama:
      base-url: http://ollama:11434
      embedding:
        options:
          model: llama3
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgres:5432/movie_db
    driver-class-name: org.postgresql.Driver
    username: // Add here
    password: // Add here
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:init.sql
        - classpath:movies.sql
        - classpath:hybrid-search-function.sql

movie:
  api-key: // Add here
