spring:
  application:
    name: movie-hybrid-search
  ai:
    ollama:
      embedding:
        options:
          model: llama3
    vectorstore:
      pgvector:
        index-type: NONE
        distance-type: COSINE_DISTANCE
        dimension: 4096
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/movie_db
    username: // Add here
    password: // Add here
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:init.sql

movie:
  api-key: // Add here
