spring:
  application:
    name: movie-hybrid-search
  ai:
    ollama:
      embedding:
        options:
          model: llama3
    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimension: 1999
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/movie_db
